### PR TITLE
Fixed Bug

### PR DESCRIPTION
**Pull request by AmirKaseb**
Screenshot 
image

### CODE REVIEW

**Comment by AmirKaseb** [comment]
With keeping same version of flask

**Review by MoustafaRoushdy — APPROVED** [review]
You could use a different version of flask or install Wergzeug with it 
don't both was unnecessary
Don't open two PR to the same feature, you could still commit to a PR wich in an open state

**Comment by AmirKaseb** [comment]
https://hub.docker.com/repository/docker/amirkasseb/amirflask/general

**Comment by AmirKaseb** [comment]
Attached the Link to the docker image pushed on docker hub

**Pull request closed without merging**
